// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXm1_NoSaZEwGJMQwrvoP0mfrg9hYSmA',
    appId: '1:953924610449:web:5a097cb0cd99bbddba1230',
    messagingSenderId: '953924610449',
    projectId: 'taskflow-1282b',
    authDomain: 'taskflow-1282b.firebaseapp.com',
    storageBucket: 'taskflow-1282b.firebasestorage.app',
    measurementId: 'G-HDQ29DE48M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEYP3xz5izUiZpDB5UjUH7EJKZ6ni1ZUc',
    appId: '1:953924610449:android:1884dd6cda6fdc23ba1230',
    messagingSenderId: '953924610449',
    projectId: 'taskflow-1282b',
    storageBucket: 'taskflow-1282b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxYW92z2Dkqc4Ky0qvrpdat35UTHmqjc',
    appId: '1:953924610449:ios:41336610261e21bcba1230',
    messagingSenderId: '953924610449',
    projectId: 'taskflow-1282b',
    storageBucket: 'taskflow-1282b.firebasestorage.app',
    iosBundleId: 'com.example.taskFlow',
  );
}
